name: "Build Check on Pull Request"
on:
  pull_request:
    types:
      - opened
      - reopened
      - unlocked
      - synchronize
    branches:
      - main
      - dev
    paths:
      - "src/**"
      - "public/**"
      - ".env.production"
jobs:
  pr-build-check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [24.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}
      - uses: pnpm/action-setup@v6
        name: Install pnpm
        with:
          version: 11.8.0
          run_install: false
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm
      - name: Install packages
        run: pnpm install --frozen-lockfile
      - name: Build pages
        run: |
          pnpm build
        env:
          NODE_OPTIONS: --max_old_space_size=4096
